# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: suspend.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsuspend.proto\x12\rpower_manager\"\xef\x01\n\x0fSuspendImminent\x12\x12\n\nsuspend_id\x18\x01 \x01(\x05\x12\x35\n\x06reason\x18\x02 \x01(\x0e\x32%.power_manager.SuspendImminent.Reason\x12\x35\n\x06\x61\x63tion\x18\x03 \x01(\x0e\x32%.power_manager.SuspendImminent.Action\"-\n\x06Reason\x12\x08\n\x04IDLE\x10\x00\x12\x0e\n\nLID_CLOSED\x10\x01\x12\t\n\x05OTHER\x10\x02\"+\n\x06\x41\x63tion\x12\x0b\n\x07SUSPEND\x10\x00\x12\x14\n\x10HIBERNATE_RESUME\x10\x01\"\xa5\x02\n\x0bSuspendDone\x12\x12\n\nsuspend_id\x18\x01 \x01(\x05\x12\x18\n\x10suspend_duration\x18\x02 \x01(\x03\x12:\n\x0bwakeup_type\x18\x03 \x01(\x0e\x32%.power_manager.SuspendDone.WakeupType\x12>\n\rdeepest_state\x18\x04 \x01(\x0e\x32\'.power_manager.SuspendDone.SuspendState\"C\n\nWakeupType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x12\n\x0eNOT_APPLICABLE\x10\x01\x12\t\n\x05INPUT\x10\x02\x12\t\n\x05OTHER\x10\x03\"\'\n\x0cSuspendState\x12\n\n\x06TO_RAM\x10\x00\x12\x0b\n\x07TO_DISK\x10\x01\"C\n\x1bRegisterSuspendDelayRequest\x12\x0f\n\x07timeout\x18\x01 \x01(\x03\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"K\n\x19RegisterSuspendDelayReply\x12\x10\n\x08\x64\x65lay_id\x18\x01 \x01(\x05\x12\x1c\n\x14min_delay_timeout_ms\x18\x02 \x01(\x05\"1\n\x1dUnregisterSuspendDelayRequest\x12\x10\n\x08\x64\x65lay_id\x18\x01 \x01(\x05\"<\n\x14SuspendReadinessInfo\x12\x10\n\x08\x64\x65lay_id\x18\x01 \x01(\x05\x12\x12\n\nsuspend_id\x18\x02 \x01(\x05\"+\n\x14\x44\x61rkResumeWakeReason\x12\x13\n\x0bwake_reason\x18\x01 \x01(\t\"*\n\x14HibernateResumeReady\x12\x12\n\nsuspend_id\x18\x01 \x01(\x05\x42-H\x03Z)chromiumos/system_api/power_manager_proto')



_SUSPENDIMMINENT = DESCRIPTOR.message_types_by_name['SuspendImminent']
_SUSPENDDONE = DESCRIPTOR.message_types_by_name['SuspendDone']
_REGISTERSUSPENDDELAYREQUEST = DESCRIPTOR.message_types_by_name['RegisterSuspendDelayRequest']
_REGISTERSUSPENDDELAYREPLY = DESCRIPTOR.message_types_by_name['RegisterSuspendDelayReply']
_UNREGISTERSUSPENDDELAYREQUEST = DESCRIPTOR.message_types_by_name['UnregisterSuspendDelayRequest']
_SUSPENDREADINESSINFO = DESCRIPTOR.message_types_by_name['SuspendReadinessInfo']
_DARKRESUMEWAKEREASON = DESCRIPTOR.message_types_by_name['DarkResumeWakeReason']
_HIBERNATERESUMEREADY = DESCRIPTOR.message_types_by_name['HibernateResumeReady']
_SUSPENDIMMINENT_REASON = _SUSPENDIMMINENT.enum_types_by_name['Reason']
_SUSPENDIMMINENT_ACTION = _SUSPENDIMMINENT.enum_types_by_name['Action']
_SUSPENDDONE_WAKEUPTYPE = _SUSPENDDONE.enum_types_by_name['WakeupType']
_SUSPENDDONE_SUSPENDSTATE = _SUSPENDDONE.enum_types_by_name['SuspendState']
SuspendImminent = _reflection.GeneratedProtocolMessageType('SuspendImminent', (_message.Message,), {
  'DESCRIPTOR' : _SUSPENDIMMINENT,
  '__module__' : 'suspend_pb2'
  # @@protoc_insertion_point(class_scope:power_manager.SuspendImminent)
  })
_sym_db.RegisterMessage(SuspendImminent)

SuspendDone = _reflection.GeneratedProtocolMessageType('SuspendDone', (_message.Message,), {
  'DESCRIPTOR' : _SUSPENDDONE,
  '__module__' : 'suspend_pb2'
  # @@protoc_insertion_point(class_scope:power_manager.SuspendDone)
  })
_sym_db.RegisterMessage(SuspendDone)

RegisterSuspendDelayRequest = _reflection.GeneratedProtocolMessageType('RegisterSuspendDelayRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERSUSPENDDELAYREQUEST,
  '__module__' : 'suspend_pb2'
  # @@protoc_insertion_point(class_scope:power_manager.RegisterSuspendDelayRequest)
  })
_sym_db.RegisterMessage(RegisterSuspendDelayRequest)

RegisterSuspendDelayReply = _reflection.GeneratedProtocolMessageType('RegisterSuspendDelayReply', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERSUSPENDDELAYREPLY,
  '__module__' : 'suspend_pb2'
  # @@protoc_insertion_point(class_scope:power_manager.RegisterSuspendDelayReply)
  })
_sym_db.RegisterMessage(RegisterSuspendDelayReply)

UnregisterSuspendDelayRequest = _reflection.GeneratedProtocolMessageType('UnregisterSuspendDelayRequest', (_message.Message,), {
  'DESCRIPTOR' : _UNREGISTERSUSPENDDELAYREQUEST,
  '__module__' : 'suspend_pb2'
  # @@protoc_insertion_point(class_scope:power_manager.UnregisterSuspendDelayRequest)
  })
_sym_db.RegisterMessage(UnregisterSuspendDelayRequest)

SuspendReadinessInfo = _reflection.GeneratedProtocolMessageType('SuspendReadinessInfo', (_message.Message,), {
  'DESCRIPTOR' : _SUSPENDREADINESSINFO,
  '__module__' : 'suspend_pb2'
  # @@protoc_insertion_point(class_scope:power_manager.SuspendReadinessInfo)
  })
_sym_db.RegisterMessage(SuspendReadinessInfo)

DarkResumeWakeReason = _reflection.GeneratedProtocolMessageType('DarkResumeWakeReason', (_message.Message,), {
  'DESCRIPTOR' : _DARKRESUMEWAKEREASON,
  '__module__' : 'suspend_pb2'
  # @@protoc_insertion_point(class_scope:power_manager.DarkResumeWakeReason)
  })
_sym_db.RegisterMessage(DarkResumeWakeReason)

HibernateResumeReady = _reflection.GeneratedProtocolMessageType('HibernateResumeReady', (_message.Message,), {
  'DESCRIPTOR' : _HIBERNATERESUMEREADY,
  '__module__' : 'suspend_pb2'
  # @@protoc_insertion_point(class_scope:power_manager.HibernateResumeReady)
  })
_sym_db.RegisterMessage(HibernateResumeReady)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003Z)chromiumos/system_api/power_manager_proto'
  _SUSPENDIMMINENT._serialized_start=33
  _SUSPENDIMMINENT._serialized_end=272
  _SUSPENDIMMINENT_REASON._serialized_start=182
  _SUSPENDIMMINENT_REASON._serialized_end=227
  _SUSPENDIMMINENT_ACTION._serialized_start=229
  _SUSPENDIMMINENT_ACTION._serialized_end=272
  _SUSPENDDONE._serialized_start=275
  _SUSPENDDONE._serialized_end=568
  _SUSPENDDONE_WAKEUPTYPE._serialized_start=460
  _SUSPENDDONE_WAKEUPTYPE._serialized_end=527
  _SUSPENDDONE_SUSPENDSTATE._serialized_start=529
  _SUSPENDDONE_SUSPENDSTATE._serialized_end=568
  _REGISTERSUSPENDDELAYREQUEST._serialized_start=570
  _REGISTERSUSPENDDELAYREQUEST._serialized_end=637
  _REGISTERSUSPENDDELAYREPLY._serialized_start=639
  _REGISTERSUSPENDDELAYREPLY._serialized_end=714
  _UNREGISTERSUSPENDDELAYREQUEST._serialized_start=716
  _UNREGISTERSUSPENDDELAYREQUEST._serialized_end=765
  _SUSPENDREADINESSINFO._serialized_start=767
  _SUSPENDREADINESSINFO._serialized_end=827
  _DARKRESUMEWAKEREASON._serialized_start=829
  _DARKRESUMEWAKEREASON._serialized_end=872
  _HIBERNATERESUMEREADY._serialized_start=874
  _HIBERNATERESUMEREADY._serialized_end=916
# @@protoc_insertion_point(module_scope)
