# Copyright 2010 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

TARGET = evtest
SRC = evtest.c

$(TARGET): $(SRC)
	$(CC) -o $@ $^

clean:
	$(RM) $(TARGET)
