#!/usr/bin/env python3
# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import argparse
import logging
import os
import sys
import re

from suite_lib import TestManager

# Export suite to protobuf format

TEMPLATE_FILE = 'suite_template.v0'

SANITIZE = r'[ \-\s]+'
NAME_RE = re.compile(r'id *= *"([^"]+)",')
BUG_RE = re.compile(r'bug_component *= *"([^"]+)",')
OWNERS_RE = re.compile(r'owners *= *\[([^\]]+)\]',
                       flags=re.MULTILINE | re.DOTALL)
CRITERIA_RE = re.compile(r'criteria *= *"([^"]+)",')


def export_suite_to_starlark(suite_name, suite_tests, starlark_path):

    # set default values for metadata
    owners = '"<TODO enter email of suite owner here can add multiple values>"'
    bug_component = 'b:<TODO bug component of suite owner here>'
    criteria = '<TODO enter brief one sentence description of the test suite here and what it validates>'
    updated = False

    try:
        # read in suite if it already exists to avoid writing over metadata
        updated, owners, bug_component, criteria = _parse_existing_suite_starlark(
                starlark_path, suite_name)
    except FileNotFoundError:
        pass

    _write_suite(suite_name, suite_tests, starlark_path, owners, bug_component,
                 criteria, updated)


def _write_suite(suite_name, suite_tests, starlark_path, owners, bug_component,
                 criteria, updated):
    # sanitize suite name by removing spaces and dashes and replacing with _
    # this allows using it as a function name in starlark
    suite_name_sanitized = re.sub(SANITIZE, '_', suite_name)
    # read in template
    template = ''
    with open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                           TEMPLATE_FILE),
              'r',
              encoding='utf-8') as f:
        template = f.read()

    # write out suite using template
    contents = template.format(
            suite_name_sanitized=suite_name_sanitized,
            suite_name=suite_name,
            test_list_str=_to_string(suite_tests),
            owners=owners,
            bug_component=bug_component,
            criteria=criteria,
    )
    with open(starlark_path, 'w', encoding='utf-8') as f:
        f.write(contents)
    if updated:
        logging.info(
                '\n\nupdated suite: %s, check diff to make sure no unexpected changes were made.',
                starlark_path)
    else:
        logging.info('\n\nwrote suite: %s.', starlark_path)


# parse existing suite starlark file to get metadata for regenerating updated
# suite, this assumes there is a single suite in the file and that the file was
# originally generated by this script, if multiple suites are detected an exception
# will be raised
#
# returns updated, owners, bug_component, criteria throws FileNotFoundError if file
# does not exist or Exception if there is a processing error
def _parse_existing_suite_starlark(starlark_path, suite_name):
    with open(starlark_path, 'r') as f:
        data = f.read()
        suite_name_parsed = _parse_from_re(NAME_RE, data)
        if suite_name_parsed != suite_name:
            raise Exception(
                    'suite name mismatch: %s != %s refusing to overwrite %s' %
                    (suite_name, suite_name_parsed, starlark_path))
        owners = _parse_from_re(OWNERS_RE, data)
        owners = owners.rstrip('\n ').lstrip('\n ')
        bug_component = _parse_from_re(BUG_RE, data)
        criteria = _parse_from_re(CRITERIA_RE, data)
        if owners is None:
            raise Exception('owners not found in %s' % starlark_path)
        if bug_component is None:
            raise Exception('bug_component not found in %s' % starlark_path)
        if criteria is None:
            raise Exception('criteria not found in %s' % starlark_path)

        updated = True

        return updated, owners, bug_component, criteria


def _parse_from_re(regex, data):
    matches = regex.finditer(data)
    ret = None
    for match in matches:
        if ret is not None:
            raise Exception(
                    "multiple suites detected cannot update starlark file")
        ret = match.group(1)
    return ret


def _to_string(test_list):
    INDENT = 12
    ret = ''
    for test in test_list:
        ret += ' ' * INDENT + '\'' + test + '\',\n'
    return ret


def main(args):
    root = logging.getLogger()
    root.setLevel(args.log)
    # change the format for the default root handler which is at index 0
    root_handler = root.handlers[0]
    root_handler.setFormatter(logging.Formatter('%(message)s'))

    suite_name = args.suite
    starlark_path = args.output

    tests = TestManager()
    basepath = os.path.dirname(os.path.abspath(__file__))
    tests.initialize_from_fs([(basepath + '/../test_suites'),
                              (basepath + '/../server/site_tests'),
                              (basepath + '/../client/site_tests')])
    tests.process_all_tests()
    suite_tests = sorted(tests.list_suite_named(suite_name))

    export_suite_to_starlark(suite_name, suite_tests, starlark_path)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument(
            "--log",
            help="Provide logging level",
            default='INFO',
            choices=[
                    'CRITICAL',
                    'ERROR',
                    'WARNING',
                    'INFO',
                    'DEBUG',
                    'NOTSET',
            ],
    )
    parser.add_argument(
            '--suite',
            help='suite to parse from autotest format',
            required=True,
    )
    parser.add_argument(
            '--output',
            help='path to file to write starlark centralized style suite to',
            required=True,
    )
    parsed_args = parser.parse_args()

    main(parsed_args)
