# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: conn_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='conn_service.proto',
  package='tast.cros.ui',
  syntax='proto3',
  serialized_options=b'Z chromiumos/tast/services/cros/ui',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x63onn_service.proto\x12\x0ctast.cros.ui\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1d\n\x0eNewConnRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"\x1d\n\x0fNewConnResponse\x12\n\n\x02id\x18\x01 \x01(\r\"&\n\x17NewConnForTargetRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"\x1a\n\x0c\x43loseRequest\x12\n\n\x02id\x18\x01 \x01(\r\"#\n\x15\x41\x63tivateTargetRequest\x12\n\n\x02id\x18\x01 \x01(\r\"*\n\x0fNavigateRequest\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0b\n\x03url\x18\x02 \x01(\t\"+\n\x0f\x43onnEvalRequest\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04\x65xpr\x18\x02 \x01(\t\"O\n\x0f\x43onnCallRequest\x12\n\n\x02id\x18\x01 \x01(\r\x12\n\n\x02\x66n\x18\x02 \x01(\t\x12$\n\x04\x61rgs\x18\x03 \x03(\x0b\x32\x16.google.protobuf.Value\"]\n\x16\x43onnWaitForExprRequest\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04\x65xpr\x18\x02 \x01(\t\x12\x14\n\x0ctimeout_secs\x18\x03 \x01(\r\x12\x13\n\x0b\x66\x61il_on_err\x18\x04 \x01(\x08\x32\x97\x05\n\x0b\x43onnService\x12H\n\x07NewConn\x12\x1c.tast.cros.ui.NewConnRequest\x1a\x1d.tast.cros.ui.NewConnResponse\"\x00\x12Z\n\x10NewConnForTarget\x12%.tast.cros.ui.NewConnForTargetRequest\x1a\x1d.tast.cros.ui.NewConnResponse\"\x00\x12=\n\x05\x43lose\x12\x1a.tast.cros.ui.CloseRequest\x1a\x16.google.protobuf.Empty\"\x00\x12<\n\x08\x43loseAll\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12O\n\x0e\x41\x63tivateTarget\x12#.tast.cros.ui.ActivateTargetRequest\x1a\x16.google.protobuf.Empty\"\x00\x12\x43\n\x08Navigate\x12\x1d.tast.cros.ui.NavigateRequest\x1a\x16.google.protobuf.Empty\"\x00\x12?\n\x04\x45val\x12\x1d.tast.cros.ui.ConnEvalRequest\x1a\x16.google.protobuf.Value\"\x00\x12?\n\x04\x43\x61ll\x12\x1d.tast.cros.ui.ConnCallRequest\x1a\x16.google.protobuf.Value\"\x00\x12M\n\x0bWaitForExpr\x12$.tast.cros.ui.ConnWaitForExprRequest\x1a\x16.google.protobuf.Empty\"\x00\x42\"Z chromiumos/tast/services/cros/uib\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_NEWCONNREQUEST = _descriptor.Descriptor(
  name='NewConnRequest',
  full_name='tast.cros.ui.NewConnRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='tast.cros.ui.NewConnRequest.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=124,
)


_NEWCONNRESPONSE = _descriptor.Descriptor(
  name='NewConnResponse',
  full_name='tast.cros.ui.NewConnResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tast.cros.ui.NewConnResponse.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=155,
)


_NEWCONNFORTARGETREQUEST = _descriptor.Descriptor(
  name='NewConnForTargetRequest',
  full_name='tast.cros.ui.NewConnForTargetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='tast.cros.ui.NewConnForTargetRequest.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=195,
)


_CLOSEREQUEST = _descriptor.Descriptor(
  name='CloseRequest',
  full_name='tast.cros.ui.CloseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tast.cros.ui.CloseRequest.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=223,
)


_ACTIVATETARGETREQUEST = _descriptor.Descriptor(
  name='ActivateTargetRequest',
  full_name='tast.cros.ui.ActivateTargetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tast.cros.ui.ActivateTargetRequest.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=260,
)


_NAVIGATEREQUEST = _descriptor.Descriptor(
  name='NavigateRequest',
  full_name='tast.cros.ui.NavigateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tast.cros.ui.NavigateRequest.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='tast.cros.ui.NavigateRequest.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=304,
)


_CONNEVALREQUEST = _descriptor.Descriptor(
  name='ConnEvalRequest',
  full_name='tast.cros.ui.ConnEvalRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tast.cros.ui.ConnEvalRequest.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expr', full_name='tast.cros.ui.ConnEvalRequest.expr', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=349,
)


_CONNCALLREQUEST = _descriptor.Descriptor(
  name='ConnCallRequest',
  full_name='tast.cros.ui.ConnCallRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tast.cros.ui.ConnCallRequest.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fn', full_name='tast.cros.ui.ConnCallRequest.fn', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='args', full_name='tast.cros.ui.ConnCallRequest.args', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=430,
)


_CONNWAITFOREXPRREQUEST = _descriptor.Descriptor(
  name='ConnWaitForExprRequest',
  full_name='tast.cros.ui.ConnWaitForExprRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tast.cros.ui.ConnWaitForExprRequest.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expr', full_name='tast.cros.ui.ConnWaitForExprRequest.expr', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timeout_secs', full_name='tast.cros.ui.ConnWaitForExprRequest.timeout_secs', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fail_on_err', full_name='tast.cros.ui.ConnWaitForExprRequest.fail_on_err', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=525,
)

_CONNCALLREQUEST.fields_by_name['args'].message_type = google_dot_protobuf_dot_struct__pb2._VALUE
DESCRIPTOR.message_types_by_name['NewConnRequest'] = _NEWCONNREQUEST
DESCRIPTOR.message_types_by_name['NewConnResponse'] = _NEWCONNRESPONSE
DESCRIPTOR.message_types_by_name['NewConnForTargetRequest'] = _NEWCONNFORTARGETREQUEST
DESCRIPTOR.message_types_by_name['CloseRequest'] = _CLOSEREQUEST
DESCRIPTOR.message_types_by_name['ActivateTargetRequest'] = _ACTIVATETARGETREQUEST
DESCRIPTOR.message_types_by_name['NavigateRequest'] = _NAVIGATEREQUEST
DESCRIPTOR.message_types_by_name['ConnEvalRequest'] = _CONNEVALREQUEST
DESCRIPTOR.message_types_by_name['ConnCallRequest'] = _CONNCALLREQUEST
DESCRIPTOR.message_types_by_name['ConnWaitForExprRequest'] = _CONNWAITFOREXPRREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NewConnRequest = _reflection.GeneratedProtocolMessageType('NewConnRequest', (_message.Message,), {
  'DESCRIPTOR' : _NEWCONNREQUEST,
  '__module__' : 'conn_service_pb2'
  # @@protoc_insertion_point(class_scope:tast.cros.ui.NewConnRequest)
  })
_sym_db.RegisterMessage(NewConnRequest)

NewConnResponse = _reflection.GeneratedProtocolMessageType('NewConnResponse', (_message.Message,), {
  'DESCRIPTOR' : _NEWCONNRESPONSE,
  '__module__' : 'conn_service_pb2'
  # @@protoc_insertion_point(class_scope:tast.cros.ui.NewConnResponse)
  })
_sym_db.RegisterMessage(NewConnResponse)

NewConnForTargetRequest = _reflection.GeneratedProtocolMessageType('NewConnForTargetRequest', (_message.Message,), {
  'DESCRIPTOR' : _NEWCONNFORTARGETREQUEST,
  '__module__' : 'conn_service_pb2'
  # @@protoc_insertion_point(class_scope:tast.cros.ui.NewConnForTargetRequest)
  })
_sym_db.RegisterMessage(NewConnForTargetRequest)

CloseRequest = _reflection.GeneratedProtocolMessageType('CloseRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLOSEREQUEST,
  '__module__' : 'conn_service_pb2'
  # @@protoc_insertion_point(class_scope:tast.cros.ui.CloseRequest)
  })
_sym_db.RegisterMessage(CloseRequest)

ActivateTargetRequest = _reflection.GeneratedProtocolMessageType('ActivateTargetRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACTIVATETARGETREQUEST,
  '__module__' : 'conn_service_pb2'
  # @@protoc_insertion_point(class_scope:tast.cros.ui.ActivateTargetRequest)
  })
_sym_db.RegisterMessage(ActivateTargetRequest)

NavigateRequest = _reflection.GeneratedProtocolMessageType('NavigateRequest', (_message.Message,), {
  'DESCRIPTOR' : _NAVIGATEREQUEST,
  '__module__' : 'conn_service_pb2'
  # @@protoc_insertion_point(class_scope:tast.cros.ui.NavigateRequest)
  })
_sym_db.RegisterMessage(NavigateRequest)

ConnEvalRequest = _reflection.GeneratedProtocolMessageType('ConnEvalRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONNEVALREQUEST,
  '__module__' : 'conn_service_pb2'
  # @@protoc_insertion_point(class_scope:tast.cros.ui.ConnEvalRequest)
  })
_sym_db.RegisterMessage(ConnEvalRequest)

ConnCallRequest = _reflection.GeneratedProtocolMessageType('ConnCallRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONNCALLREQUEST,
  '__module__' : 'conn_service_pb2'
  # @@protoc_insertion_point(class_scope:tast.cros.ui.ConnCallRequest)
  })
_sym_db.RegisterMessage(ConnCallRequest)

ConnWaitForExprRequest = _reflection.GeneratedProtocolMessageType('ConnWaitForExprRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONNWAITFOREXPRREQUEST,
  '__module__' : 'conn_service_pb2'
  # @@protoc_insertion_point(class_scope:tast.cros.ui.ConnWaitForExprRequest)
  })
_sym_db.RegisterMessage(ConnWaitForExprRequest)


DESCRIPTOR._options = None

_CONNSERVICE = _descriptor.ServiceDescriptor(
  name='ConnService',
  full_name='tast.cros.ui.ConnService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=528,
  serialized_end=1191,
  methods=[
  _descriptor.MethodDescriptor(
    name='NewConn',
    full_name='tast.cros.ui.ConnService.NewConn',
    index=0,
    containing_service=None,
    input_type=_NEWCONNREQUEST,
    output_type=_NEWCONNRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='NewConnForTarget',
    full_name='tast.cros.ui.ConnService.NewConnForTarget',
    index=1,
    containing_service=None,
    input_type=_NEWCONNFORTARGETREQUEST,
    output_type=_NEWCONNRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Close',
    full_name='tast.cros.ui.ConnService.Close',
    index=2,
    containing_service=None,
    input_type=_CLOSEREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CloseAll',
    full_name='tast.cros.ui.ConnService.CloseAll',
    index=3,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ActivateTarget',
    full_name='tast.cros.ui.ConnService.ActivateTarget',
    index=4,
    containing_service=None,
    input_type=_ACTIVATETARGETREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Navigate',
    full_name='tast.cros.ui.ConnService.Navigate',
    index=5,
    containing_service=None,
    input_type=_NAVIGATEREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Eval',
    full_name='tast.cros.ui.ConnService.Eval',
    index=6,
    containing_service=None,
    input_type=_CONNEVALREQUEST,
    output_type=google_dot_protobuf_dot_struct__pb2._VALUE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Call',
    full_name='tast.cros.ui.ConnService.Call',
    index=7,
    containing_service=None,
    input_type=_CONNCALLREQUEST,
    output_type=google_dot_protobuf_dot_struct__pb2._VALUE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='WaitForExpr',
    full_name='tast.cros.ui.ConnService.WaitForExpr',
    index=8,
    containing_service=None,
    input_type=_CONNWAITFOREXPRREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONNSERVICE)

DESCRIPTOR.services_by_name['ConnService'] = _CONNSERVICE

# @@protoc_insertion_point(module_scope)
