# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lacros_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lacros_service.proto',
  package='tast.cros.browser',
  syntax='proto3',
  serialized_options=b'Z chromiumos/tast/services/cros/ui',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14lacros_service.proto\x12\x11tast.cros.browser\x1a\x1bgoogle/protobuf/empty.proto\"#\n\x14LaunchWithURLRequest\x12\x0b\n\x03url\x18\x01 \x01(\t2\x97\x02\n\rLacrosService\x12:\n\x06Launch\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12R\n\rLaunchWithURL\x12\'.tast.cros.browser.LaunchWithURLRequest\x1a\x16.google.protobuf.Empty\"\x00\x12;\n\x07\x43onnect\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12\x39\n\x05\x43lose\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x42\"Z chromiumos/tast/services/cros/uib\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_LAUNCHWITHURLREQUEST = _descriptor.Descriptor(
  name='LaunchWithURLRequest',
  full_name='tast.cros.browser.LaunchWithURLRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='tast.cros.browser.LaunchWithURLRequest.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=107,
)

DESCRIPTOR.message_types_by_name['LaunchWithURLRequest'] = _LAUNCHWITHURLREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LaunchWithURLRequest = _reflection.GeneratedProtocolMessageType('LaunchWithURLRequest', (_message.Message,), {
  'DESCRIPTOR' : _LAUNCHWITHURLREQUEST,
  '__module__' : 'lacros_service_pb2'
  # @@protoc_insertion_point(class_scope:tast.cros.browser.LaunchWithURLRequest)
  })
_sym_db.RegisterMessage(LaunchWithURLRequest)


DESCRIPTOR._options = None

_LACROSSERVICE = _descriptor.ServiceDescriptor(
  name='LacrosService',
  full_name='tast.cros.browser.LacrosService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=110,
  serialized_end=389,
  methods=[
  _descriptor.MethodDescriptor(
    name='Launch',
    full_name='tast.cros.browser.LacrosService.Launch',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='LaunchWithURL',
    full_name='tast.cros.browser.LacrosService.LaunchWithURL',
    index=1,
    containing_service=None,
    input_type=_LAUNCHWITHURLREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Connect',
    full_name='tast.cros.browser.LacrosService.Connect',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Close',
    full_name='tast.cros.browser.LacrosService.Close',
    index=3,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LACROSSERVICE)

DESCRIPTOR.services_by_name['LacrosService'] = _LACROSSERVICE

# @@protoc_insertion_point(module_scope)
