#!/usr/bin/python3 -u

import os
import sys
import os

dir_name = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(dir_name, 'beta_list')) as rf:
    betalist = rf.read().splitlines()

test_name = None
if "--control-name" in sys.argv:
    try:
        test_name = sys.argv[sys.argv.index('--control-name') + 1]
    except IndexError:
        raise Exception("No test name followed --control-name flag")
elif "-l" in sys.argv:
    try:
        label = sys.argv[sys.argv.index('-l') + 1]
        test_name = label.split("/")[-1]
    except IndexError:
        raise Exception("No job name followed -l flag")

if test_name and (test_name in betalist or 'tast.' in test_name):
    os.environ["PY_VERSION"] = "3"
    v = 3
else:
    os.environ["PY_VERSION"] = "2"
    v = 2

os.system("python{} {} {}".format(v, os.path.join(dir_name, '_autoserv'), ' '.join(sys.argv[1:])))
